import { ReactNode } from 'react'
import { Header } from '@/components/Header'
import { More } from '@/components/More'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="flex bg-zinc-950 text-zinc-50">
        <Header />
        {children}
        <More />
      </body>
    </html>
  )
}
